In [ ]:
## original code

import numpy as np

def step(grid):
    rows, cols = grid.shape
    for i in range(rows):
        for j in range(cols):
            neighbours = get_neighbours(grid, i, j)
            count = sum(neighbours)            
            # cells are unaffected unless they:
            # - die of under- or overpopulation, or
            # - become alive if they have exactly three neighbours
            if count < 2 or count > 3:
                grid[i, j] = 0
            elif count == 3:
                grid[i, j] = 1
                 
def get_neighbours(grid, i, j):
    rows, cols = grid.shape
    indices = np.array([(i-1, j-1), (i-1, j), (i-1, j+1),
                        (i, j-1),             (i, j+1),
                        (i+1, j-1), (i+1, j), (i+1, j+1)])
    valid_indices = (indices[:, 0] >= 0) & (indices[:, 0] < rows) & \
                    (indices[:, 1] >= 0) & (indices[:, 1] < cols)
    return grid[indices[valid_indices][:, 0], indices[valid_indices][:, 1]]

# Test
grid = np.array([[0, 0, 0, 0, 0],
                 [0, 0, 1, 0, 0],
                 [0, 1, 1, 1, 0],
                 [0, 0, 1, 0, 0],
                 [0, 0, 0, 0, 0]], dtype=np.int8)
step(grid)
print(grid)

# our grid should show a square pattern, but doesn't
expected_grid = np.array([[0, 0, 0, 0, 0],
                          [0, 1, 1, 1, 0],
                          [0, 1, 0, 1, 0],
                          [0, 1, 1, 1, 0],
                          [0, 0, 0, 0, 0]], dtype=np.int8)
assert np.array_equal(grid, expected_grid)

In [5]:
## refactored code

import numpy as np 

# define step as a pure function not impure
def step(grid):
    # create a copy of the grid to avoid in-place modifications
    new_grid = grid.copy()

    # perform operations on the copy
    rows, cols = grid.shape  # Use original grid dimensions
    for i in range(rows):
        for j in range(cols):
            neighbours = get_neighbours(grid, i, j)
            count = sum(neighbours)            
            # cells are unaffected unless they:
            # - die of under- or overpopulation, or
            # - become alive if they have exactly three neighbours
            if count < 2 or count > 3:
                new_grid[i, j] = 0
            elif count == 3:
                new_grid[i, j] = 1
    
    # return new grid 
    return new_grid

def get_neighbours(grid, i, j):
    rows, cols = grid.shape
    indices = np.array([(i-1, j-1), (i-1, j), (i-1, j+1),
                        (i, j-1),             (i, j+1),
                        (i+1, j-1), (i+1, j), (i+1, j+1)])
    valid_indices = (indices[:, 0] >= 0) & (indices[:, 0] < rows) & \
                    (indices[:, 1] >= 0) & (indices[:, 1] < cols)
    return grid[indices[valid_indices][:, 0], indices[valid_indices][:, 1]]

# Test
grid = np.array([[0, 0, 0, 0, 0],
                 [0, 0, 1, 0, 0],
                 [0, 1, 1, 1, 0],
                 [0, 0, 1, 0, 0],
                 [0, 0, 0, 0, 0]], dtype=np.int8)

# assigning grid to an object
grid = step(grid)
print(grid)

# our grid should show a square pattern, but doesn't
expected_grid = np.array([[0, 0, 0, 0, 0],
                          [0, 1, 1, 1, 0],
                          [0, 1, 0, 1, 0],
                          [0, 1, 1, 1, 0],
                          [0, 0, 0, 0, 0]], dtype=np.int8)
assert np.array_equal(grid, expected_grid)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 0 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [ ]:
class Node(object):
    "Generic tree node."
    def __init__(self, name='root', children=None):
        self.value = name
        self.children = children or []

    def __repr__(self):
        return f"Node({self.value}, {self.children})"

t = Node('+', [Node('1'),
               Node('*', [Node('2'),
                          Node('3')])])

# function that traverses tree and returns total number of nodes
def count_nodes(tree):
    if tree is None:
        return 0
    count = 1 
    for child in tree.children:
        count += count_nodes(child) 
    return count

# function that traverses tree and returns result of expression
def evaluate(tree):
    if tree is None:
        return 0
    if not tree.children:
        return int(tree.value)
    if tree.value == '+':
        return sum(evaluate(child) for child in tree.children)
    elif tree.value == '*':
        result = 1
        for child in tree.children:
            result *= evaluate(child)
        return result
    else:
        raise ValueError(f"Unknown operator: {tree.value}")
     

In [ ]:
from functools import reduce

def sum_of_squares(numbers):
    return reduce(lambda x, y: x + y, map(lambda x: x**2, numbers))

print(sum_of_squares([0]))
print(sum_of_squares([1]))
print(sum_of_squares([1, 2, 3]))
print(sum_of_squares([-1]))
print(sum_of_squares([-1, -2, -3]))



In [15]:
def sum_of_squares(l):
    return reduce(lambda x, y: x + y, map(lambda x: int(x)**2 if '#' not in x else 0, l))

print(sum_of_squares(['1', '2', '3']))
print(sum_of_squares(['-1', '-2', '-3']))
print(sum_of_squares(['1', '2', '#100', '3']))


14
14
14


In [19]:
import time

def time_it(func):
    def wrapper(*args, **kwargs):
        start_time = time.process_time_ns()  
        result = func(*args, **kwargs)                
        end_time = time.process_time_ns()   
        elapsed_time = end_time - start_time
        print(f"Time taken: {elapsed_time} nanoseconds")
        return result
    return wrapper

@time_it
def measure_me(n):
    total = 0
    for i in range(n):
        total += i * i
    return total

measure_me(1000000)

Time taken: 30085000 nanoseconds


333332833333500000