# Procedural Programming
## Variables 
### Sorting out references

In [1]:
first, second = 1, 2
third, fourth = second, first
print(third, fourth)

2 1


## Containers
### Slicing things from the end

In [2]:
string_for_slicing = "Observation date: 02-Feb-2013"
list_for_slicing = [["fluorine", "F"],
                    ["chlorine", "Cl"],
                    ["bromine", "Br"],
                    ["iodine", "I"],
                    ["astatine", "At"]]

print(string_for_slicing)
print(list_for_slicing)

Observation date: 02-Feb-2013
[['fluorine', 'F'], ['chlorine', 'Cl'], ['bromine', 'Br'], ['iodine', 'I'], ['astatine', 'At']]


In [6]:
print (string_for_slicing[-4:])
print(list_for_slicing[1:5])

2013
[['chlorine', 'Cl'], ['bromine', 'Br'], ['iodine', 'I'], ['astatine', 'At']]


## Functions
### Combining strings

In [ ]:
def fence (str1, str2):
    return str1 + str2

print(fence("name","*"))

In [10]:
def say_hello(greeting = 'Hello', name = 'World'):
    return greeting + name + '!'

print(say_hello())
print (say_hello(name='Python'))
print (say_hello(greeting='Hi, ', name='JavaScript'))
print (say_hello(name='Hi, ', greeting='JavaScript'))
print (say_hello('World', 'Hello, '))
print (say_hello('Hello, ', 'World'))

HelloWorld!
HelloPython!
Hi, JavaScript!
JavaScriptHi, !
WorldHello, !
Hello, World!


### managing academics

In [12]:
# structure
academics = [
    {
        'name': 'Alice',
        'papers': [
            {
                'title': 'My science paper',
                'date': 2015
            },
            {
                'title': 'My other science paper',
                'date': 2017
            }
        ]
    },
    {
        'name': 'Bob',
        'papers': [
            {
                'title': 'Bob writes about science',
                'date': 2018
            }
        ]
    }
]

# adding new papers
def write_paper(academics, name, title, date):
    paper = {
        'title': title,
        'date': date
    }

    for academic in academics:
        if academic['name'] == name:
            academic['papers'].append(paper)
            break

### passing lists to functions

In [11]:
def append_to_list(l):
    l.append('appended')
    l = [1, 2, 3]
    l.append('again')
    return l

a_list = ['this', 'is', 'a', 'list']

print(append_to_list(a_list))
print(a_list)

[1, 2, 3, 'again']
['this', 'is', 'a', 'list', 'appended']


- The reason for this behaviour is that lists are mutable so when we pass one in to a function any modifications are made to the actual list as it exist in memory. 
- Using = to assign a new value creates a new list in memory (it does not modify the existing list) and assigns it to the variable / name l. 
- Any changes made to l after this are changes to the new list, so do not affect the previous list. 
- The original list still exists, but l no longer points to it. 
- Only the variable name a_list still points to the original.
- For this reason it can be useful to think of the = sign as binding a value to a name.

In [15]:
def count_papers (academics): 

    total = 0
    for academic in academics:
        total += len(academic['papers'])
    return total

print(count_papers(academics))

3


In [21]:
print (len(academics[1]['papers']))

1


In [23]:
def count_papers (academics): 
    total = 0  
    for i in range(len(academics)): 
       total += len(academics[i]['papers'])
    return total
print(count_papers(academics))

3


In [24]:
def list_papers (academics): 
    titles = []
    for academic in academics: 
        for paper in academic['papers']:
            titles.append (paper['title'])
    return titles
print(list_papers(academics))

['My science paper', 'My other science paper', 'Bob writes about science']


In [26]:
def list_papers(academics):
    papers = []

    for academic in academics:
        papers = papers + academic['papers']

    return papers
print(list_papers(academics))

[{'title': 'My science paper', 'date': 2015}, {'title': 'My other science paper', 'date': 2017}, {'title': 'Bob writes about science', 'date': 2018}]


## Arrays

In [28]:
import numpy as np

In [33]:
my_array = np.array(range(5))
my_array / 2

array([0. , 0.5, 1. , 1.5, 2. ])

### inflamation case study

In [39]:
# loading data
data = np.loadtxt(fname='inflammation/data/inflammation-01.csv', delimiter=',')
data

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [ ]:
data.shape # 60 rows, 40 columns

(60, 40)

In [ ]:
# accessing specific values
data[0,0] # first row, first column
data[0:4,0] # first four rows, first column
data[30,20] # middle
data[0:4, 0:10] 

array([[0., 0., 1., 3., 1., 2., 4., 7., 8., 3.],
       [0., 1., 2., 1., 2., 1., 3., 2., 2., 6.],
       [0., 1., 1., 3., 3., 2., 6., 2., 5., 9.],
       [0., 0., 2., 0., 4., 2., 2., 1., 6., 7.]])

In [44]:
x = np.arange(5)
y = np.copy(x)
y[2] = 0
x


array([0, 1, 2, 3, 4])

In [46]:
x = np.arange(5)
z = x 
z[2] = 0
print(x)

[0 1 0 3 4]


In [47]:
type(z)

numpy.ndarray

In [48]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
print('A = ')
print(A)

B = np.hstack([A, A])
print('B = ')
print(B)

C = np.vstack([A, A])
print('C = ')
print(C)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
# creating copy of data array
data_for_slicing = data.copy()

# slice first and last col of data
first = data_for_slicing[:,0]
last = data_for_slicing[:,-1]

# stack into 60x2 array
stacked = np.vstack([first, last])
print (stacked.shape)
print(stacked)

(2, 60)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0.
  1. 0. 1. 1. 0. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 0. 1.
  0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]]
